server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: CarsStore
springdoc:
  api-docs:
    path: /api-docs.json
  swagger-ui:
    path: /docs/index.html
    enabled: true
    use-root-path: true
  default-produces-media-type: application/json  