server:
  port: 8080

spring:
  application:
    name: CarsStore
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
springdoc:
  api-docs:
    path: /api-docs.json
  swagger-ui:
    path: /docs/index.html
    enabled: true
    use-root-path: true
  default-produces-media-type: application/json  