spring:
  kafka:
    bootstrap-servers: 10.0.1.105:9093
  datasource:
    url: jdbc:postgresql://10.0.1.105:5432/cars
    username: cars
    password: cars
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
